### ISSUE TITLE
multiple time button clicking

### ISSUE THREAD

**Issue by moli-debugger** [wTechnoo/ConsoleButtons#1]
only one time i can able to do action while clicking the button again i pressed means no changes in console.

How to use a button nth tiime to print some statements.

code that i tried:
```

            ConsoleClick consoleClick = new ConsoleClick();

            consoleClick.Initialize();

            //Button constructor that auto detects the COLLIDER WIDTH based on how many characters there are on the text.
            Button button = new Button("Sign Up", 0, 0);
            button.OnHoverOver += () => { button.WriteWithColor(Color.Gray); };
            button.OnHoverStop += () => { button.WriteWithNoColor(); };
            button.OnClick += () => { button.WriteWithColor(Color.Red); Thread.Sleep(50) ; Console.WriteLine("vanakkam");  };
            button.OnHold += () => { button.WriteWithColor(Color.Red);  };



            consoleClick.AddToComponents(button);

            while (true)
            {
               
                consoleClick.Update();
                
            }
```

**Comment by wTechnoo** [comment]
Hello moli, could you tell me which version are you using?

**Comment by moli-debugger** [comment]
Iam using 2.3.0 version of consolebutton in visual studio 2019

**Comment by wTechnoo** [comment]
What's the expected output? "Vanakkam" should be written down each time the button is clicked?

**Comment by moli-debugger** [comment]
Yes, you got my point :)

**Comment by wTechnoo** [comment]
So sadly for now, you will have to use a workaround if that's ok with you.

```C#
int i = 0;
button.OnClick += () => { button.WriteWithColor(Color.Red); Thread.Sleep(50); Console.SetCursorPosition(Console.CursorLeft, Console.CursorTop+i); Console.WriteLine("vanakkam"+i); i++; };
```

You will have to increment and set the Console write position for text by hand before printing "vanakkam".

One more thing I forgot to mention, scrolling won't work because the buttons needs to be updated each loop, that means that console focuses on the text and "bugs" the scroll

**Comment by moli-debugger** [comment]
It's OK I will manage by clear the  screen or any other process to avoid scroll till next release from your side. Well, does the above code will help me to overcome my issues?? If yes means thank you advance.

**Comment by wTechnoo** [comment]
Yes, it will.
