### ISSUE TITLE
Multiple buttons using for loop

### ISSUE THREAD

**Issue by moli-debugger** [wTechnoo/ConsoleButtons#2]
I need to create 20 button continuously but iam facing struggling in Button objname = new Button()

20 button having same objname so I can't able to do interaction(click) 

How to avoid or assign different objects name inside for loop dynamically

**Comment by wTechnoo** [comment]
Could you send me a sample of the code please?

**Comment by moli-debugger** [comment]
Sure,

  for (int k = 0; k <20; k++)
            {


                int x_location = 1, y_location = 1;

                foreach (var url in n)
                {
                    Button button = new Button(url.Title, x_location, y_location);// = new Button(url.Title, x_location, y_location);
                    button.OnHoverOver += () => { button.WriteWithColor(Color.Blue); };
                    button.OnHoverStop += () => { button.WriteWithNoColor(); };
                    int i = 0;
                    button.OnClick += () => { button.WriteWithColor(Color.Red); Thread.Sleep(5); Console.SetCursorPosition(Console.CursorLeft, Console.CursorTop + i); link(url.Url); i++; };
                    button.OnHold += () => { button.WriteWithColor(Color.Red); };

                    consoleClick.AddToComponents(button);

                    y_location += 2;
                }
            }
           // Console.ReadLine();
            while (true)
            {
                consoleClick.Update();
            }



motto of this code to create 20 button where as due to same obj name(button). It is not clickable/responding. If we assign obj name different for all 20 means then i think we can access those button.but i dont know to assign object name differently when i try k variable it shows error as local variable name cannot be object name.

**Comment by wTechnoo** [comment]
So first of all, are you using the latest version? If not, please update to the latest (2.4.0).
Second, you need 20 buttons for each URL? Cause right now, you're creating 20 buttons for EACH URL.

**Comment by moli-debugger** [comment]
ok i will check my version and yes,I need 20 buttons for each url

**Comment by moli-debugger** [comment]
after update...

![image](https://user-images.githubusercontent.com/60547028/147803393-ac6aa3eb-2a3e-43ec-878c-5b869f46564f.png)


error

Error	CS1061	'UIManager' does not contain a definition for 'Initialize' and no accessible extension method 'Initialize' accepting a first argument of type 'UIManager' could be found (are you missing a using directive or an assembly reference?)	FirtApp-console	D:\DotNet\console\FirtApp-console\FirtApp-console\Program.cs	166	Active

**Comment by wTechnoo** [comment]
Check the main page for the new example usage
Screenshot:
![image](https://user-images.githubusercontent.com/71846381/147805383-1df6dbfa-e831-413b-a3eb-64df32df6852.png)

One more thing, you're using:
```csharp
Console.SetCursorPosition(Cursor.Top + k); Console.WriteLine("text"); k++;
```

you can switch that to:
```csharp
manager.WriteLine("text");
```

**Comment by moli-debugger** [comment]
Yeah I followed but the object manager.Initilizer() shows me error continously,so may I know that am I need to write any class or install any package for UIManager

**Comment by moli-debugger** [comment]
> So first of all, are you using the latest version? If not, please update to the latest (2.4.0). Second, you need 20 buttons for each URL? Cause right now, you're creating 20 buttons for EACH URL.

Any suggestions for 20 buttons

**Comment by wTechnoo** [comment]
**manager.Initialize()** is not needed anymore, you can remove it.

Now for the 20 buttons, it should work without errors, could you send the the entire project so I could give it a test and find the error?

**Comment by wTechnoo** [comment]
I'll close this for now, if you still didn't solve it, open another issue please.
