### ISSUE TITLE
Example not works with NUGET package and main branch

### ISSUE THREAD

**Issue by UnrealKaraulov** [wTechnoo/ConsoleButtons#6]
I tried compile with nuget package, and without nuget package. 
But anyway got same result: Nothing works.

Left part of screen - example from readme
Right part of screen - result after compile and run

![image](https://user-images.githubusercontent.com/88730285/154215799-a32011d2-8e46-457d-b3af-153ce6253b33.png)

**Comment by wTechnoo** [comment]
Man please, stop opening new issues and try using older versions as I said, I don't have time to fix and release a new version right now.

**Comment by UnrealKaraulov** [comment]
@wTechnoo lol...)))
