### ISSUE TITLE
errors when building the project

### ISSUE THREAD

**Issue by Leifern6911** [wTechnoo/ConsoleButtons#7]
Hello wTechnoo, when i try to build the project i get 3 errors.

1. Aqua color not found
2. when i try to change the aqua color, the error will go to the slider.
3. When i remove the slider and build the project, after i run the project i get a error that i can't use 0 values, i have never gotten this error before so i was confused.

is there anyway i can contact you on something? so we can talk.

**Comment by wTechnoo** [comment]
Hello Leifern, thanks for giving my project a chance! 
Really appreciate it, the thing is that I don't update this package there is a long time.
I don't have the time to do it currently and I'm not sure whether the latest build works or not, you could try using a version before the latest, I think that one should work

**Comment by Leifern6911** [comment]
Hey wTechnoo, i fixed the code for you, if u want i can pull request it :D there was just 2 lines that was outdated.
